[package]
name = "rlox"
version = "0.1.0"
edition = "2021"
authors = ["Alex Wakefield <contact@alexwakefield.com>"]
description = "Lox interpreter"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
