[package]
name = "rlox"
version = "0.1.0"
edition = "2021"
authors = ["Alex Wakefield <contact@alexwakefield.com>"]
description = "Lox interpreter"
license = "MIT"

[features]
tracing = []

[dependencies]
thiserror = "1.0"

[dev-dependencies]
cfg-if = "1.0"
